server:
  port: 8761
# 安全认证的配置  
security:  
  basic:  
    enabled: true  
  user:  
    name: admin  # 用户名  
    password: 111   # 用户密码  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
