spring:
    #应用唯一标识
    application:
        name: consumer-feign
server:
    port: 9001
    tomcat:
        uri-encoding: UTF-8
# 安全认证的配置  
security:  
  basic:  
    enabled: true  
  user:  
    name: admin  # 用户名  
    password: 111   # 用户密码  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
feign:
  hystrix:  
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.example.SimpleErrorDecoder
        retryer: com.example.SimpleRetryer
        requestInterceptors:
          - com.example.FooRequestInterceptor
          - com.example.BarRequestInterceptor
        decode404: false